server:
  port : 8085

eureka:
  instance:
    hostname : localhost
  application:
    name : eureka-provider
  client:
    registerWithEureka : false
    fetchRegistry : false
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
      enable-self-preservation: true